environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - MINGW_ARCH: x86_64
    MINGW_ROOT: C:\msys64\mingw64
    BOOST_ROOT: C:\msys64\mingw64
    BOOST_LIBRARYDIR: C:\msys64\mingw64\lib
    BOOST_INCLUDEDIR: C:\msys64\mingw64\include\boost
    CMAKE_GENERATOR: 'MSYS Makefiles'

install:
  - choco install -y mingw
  - choco install -r -y ninja
  - choco install -y winflexbison
  - choco install -y swig
	- set PATH=%BOOST_LIBRARYDIR%;%PATH%
	- set PATH=%MINGW_ROOT%\bin;C:\msys64\usr\bin\;%PATH%
	- bash -lc "pacman --needed --noconfirm -S mingw-w64-%MINGW_ARCH%-boost"

build_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - ninja
